name: Build PerformanceTool and deply it to github.io

concurrency: Build and upload

on:
  push:
    paths:
      - PerformanceTool/**
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build PerformanceTool
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - run: dotnet workload install wasm-tools
      - run: dotnet publish -c Release -p:WasmCompileOptimizationFlag="-O3" -p:EmccLinkOptimizationFlag="-O3" -p:RunAOTCompilation=true PerformanceTool/PerformanceTool.csproj
      - uses: actions/upload-pages-artifact@v3
        with:
          artifact-name: github-pages
          path: PerformanceTool/bin/Release/net8.0-browser/publish/wwwroot

  deploy:
    name: Deploy to github.io
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
